name: Update Markdown Snippets

on:
  push:
  workflow_dispatch:

jobs:
  format_and_snippets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v7
    - run: ./run_mdsnippets
    - run: ./build-and-test
    - name: Check for changes
      id: git-status
      run: echo "changed=$(git status --porcelain | wc -l)" >> "$GITHUB_OUTPUT"
    - name: Git Commit and Push
      if: steps.git-status.outputs.changed != '0'
      uses: github-actions-x/commit@v2.9
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        commit-message: ". d update markdown snippets"
        rebase: 'true'
        name: Github Actions
        email: actions@github.com
